# Generated by Django 5.0.7 on 2024-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="fee",
            field=models.IntegerField(),
        ),
    ]
