# Generated by Django 5.0.7 on 2024-09-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_registration_full_name_alter_registration_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
